<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</head>
<style>
    body {
        background-image: url("https://www.google.com/imgres?imgurl=https%3A%2F%2Fmf.b37mrtl.ru%2Frussian%2Fimages%2F2017.09%2Farticle%2F59b14cd0183561754b8b458e.jpg&tbnid=wHNvnhzhbcvfxM&vet=12ahUKEwjc0qyPn-v_AhWI6CoKHQ-pDqgQMygKegUIARCXAQ..i&imgrefurl=https%3A%2F%2Frussian.rt.com%2Fscience%2Farticle%2F427416-dyadya-sem-ssha&docid=HHBhLYNQ7XISfM&w=827&h=465&q=ты%20нужен%20армии%20сша&client=safari&ved=2ahUKEwjc0qyPn-v_AhWI6CoKHQ-pDqgQMygKegUIARCXAQ");
        background-size: cover;
        background-position: center;
    }
</style>
<body>
<p><b>Ошибка</b></p>
<p>Вы неправильно ввели данные!</p>
<a href="/login" class="btn btn-outline-success my-2 my-sm-0">Попробовать Заново</a>
<p class="title mt-5">Если у вас нет аккаунта вы можете зарегестрироваться по кнопке "Регистрация"</p>
<a href="/register" class="btn btn-outline-success my-2 my-sm-0">Регистрация</a>

</body>
</html>