<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }

        .container {
            text-align: center;
        }

        .btn-group {
            margin-top: 10px;
        }
    </style>
    <title>Document</title>
</head>
<body>
<div class="container">
    <h1>Регистрация не удалась</h1>
    <h2>Может быть вы вели пустую строку или зарегистрированный email</h2>
    <div class="btn-group">
        <div class="btn-group">
            <a href="/register" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Попробуйте еще раз</a>
            <a href="https://youtu.be/DjeiLzaVQG0" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">Послушать музыку</a>
        </div>
    </div>
</div>
</body>
</html>

